<?php
/**
 * SalesInvoice
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightpearlApiClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Annex\TenantBundle\Services\BrightpearlApiClient\Model;

use \ArrayAccess;
/**
 * SalesInvoice Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     BrightpearlApiClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesInvoice implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'header' => '\Annex\TenantBundle\Services\BrightpearlApiClient\Model\SalesInvoiceHeader',
        'lines' => '\Annex\TenantBundle\Services\BrightpearlApiClient\Model\SalesInvoiceLine[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'header' => 'header',
        'lines' => 'lines'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'header' => 'setHeader',
        'lines' => 'setLines'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'header' => 'getHeader',
        'lines' => 'getLines'
    );
  
    
    /**
      * $header 
      * @var \BrightpearlApiClient\Model\SalesInvoiceHeader
      */
    protected $header;
    
    /**
      * $lines 
      * @var \BrightpearlApiClient\Model\SalesInvoiceLine[]
      */
    protected $lines;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->header = $data["header"];
            $this->lines = $data["lines"];
        }
    }
    
    /**
     * Gets header
     * @return \BrightpearlApiClient\Model\SalesInvoiceHeader
     */
    public function getHeader()
    {
        return $this->header;
    }
  
    /**
     * Sets header
     * @param \BrightpearlApiClient\Model\SalesInvoiceHeader $header
     * @return $this
     */
    public function setHeader($header)
    {
        
        $this->header = $header;
        return $this;
    }
    
    /**
     * Gets lines
     * @return \BrightpearlApiClient\Model\SalesInvoiceLine[]
     */
    public function getLines()
    {
        return $this->lines;
    }
  
    /**
     * Sets lines
     * @param \BrightpearlApiClient\Model\SalesInvoiceLine[] $lines
     * @return $this
     */
    public function setLines($lines)
    {
        
        $this->lines = $lines;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
