services:
#    annex_tenant.example:
#        class: Annex\TenantBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#### SERVICES REQUIRED BY [MODIFIED] DEPENDENCIES ####

    app.form.registration:
        class: Annex\TenantBundle\Form\RegistrationType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: app_user_registration }

#### ANNEX CORE SERVICES ####

    doctrine.dbal.connection_factory:
        class: Annex\TenantBundle\Account\CustomConnectionFactory
        arguments:
            - "@session"
            - "@request_stack"
            - "%app_info.tenant_db%"
            - "%app_info.domain%"

    annex_tenant.tenant_information:
        class: Annex\TenantBundle\Services\TenantService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%app_info.tenant_db%"

#### PAYMENT SERVICES ####
    service.stripe:
        class: Annex\TenantBundle\Services\StripeHandler
        arguments:
            - "%stripe_private_key%"
            - "%app_info.currency%"

#### BRIGHTPEARL HELPER SERVICES ####

    service.brightpearl.utility:
        class: Annex\TenantBundle\Services\Brightpearl\Utility
        arguments:
            - "@service_container"
            - "@doctrine.orm.entity_manager"