services:
#    annex_tenant.example:
#        class: Annex\TenantBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#### SERVICES REQUIRED BY [MODIFIED] DEPENDENCIES ####

    app.form.registration:
        class: Annex\TenantBundle\Form\RegistrationType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: app_user_registration }

#### ANNEX CORE SERVICES ####

    annex_tenant.settings:
        class: Annex\TenantBundle\Services\Settings
        arguments:
            - "@doctrine.orm.entity_manager"

    doctrine.dbal.connection_factory:
        class: Annex\TenantBundle\Account\CustomConnectionFactory
        arguments:
            - "@session"
            - "@service_container"

    annex_tenant.tenant_information:
        class: Annex\TenantBundle\Services\TenantService
        arguments:
            - "@session"
            - "@doctrine.orm.entity_manager"

#### BRIGHTPEARL HELPER SERVICES ####
# Allows us to change the API client without changing any other code #

    service.brightpearl.contact:
        class: Annex\TenantBundle\Services\Brightpearl\Contact
        arguments:
            - "@service_container"
            - "@annex_tenant.tenant_information"
            - "@annex_tenant.settings"

    service.brightpearl.order:
        class: Annex\TenantBundle\Services\Brightpearl\Order
        arguments:
            - "@service_container"
            - "@annex_tenant.tenant_information"
            - "@annex_tenant.settings"

    service.brightpearl.utility:
        class: Annex\TenantBundle\Services\Brightpearl\Utility
        arguments:
            - "@service_container"
            - "@annex_tenant.tenant_information"
            - "@doctrine.orm.entity_manager"