<?php
/**
 * AccountPayment
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightpearlApiClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightpearlApiClient\Model;

use \ArrayAccess;
/**
 * AccountPayment Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     BrightpearlApiClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountPayment implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'supplier_id' => 'int',
        'payment' => '\BrightpearlApiClient\Model\MonetaryValue',
        'reference_number' => 'string',
        'nominal_code' => 'string',
        'tax_date' => 'string',
        'channel_id' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'supplier_id' => 'supplierId',
        'payment' => 'payment',
        'reference_number' => 'referenceNumber',
        'nominal_code' => 'nominalCode',
        'tax_date' => 'taxDate',
        'channel_id' => 'channelId'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'supplier_id' => 'setSupplierId',
        'payment' => 'setPayment',
        'reference_number' => 'setReferenceNumber',
        'nominal_code' => 'setNominalCode',
        'tax_date' => 'setTaxDate',
        'channel_id' => 'setChannelId'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'supplier_id' => 'getSupplierId',
        'payment' => 'getPayment',
        'reference_number' => 'getReferenceNumber',
        'nominal_code' => 'getNominalCode',
        'tax_date' => 'getTaxDate',
        'channel_id' => 'getChannelId'
    );
  
    
    /**
      * $supplier_id 
      * @var int
      */
    protected $supplier_id;
    
    /**
      * $payment 
      * @var \BrightpearlApiClient\Model\MonetaryValue
      */
    protected $payment;
    
    /**
      * $reference_number 
      * @var string
      */
    protected $reference_number;
    
    /**
      * $nominal_code 
      * @var string
      */
    protected $nominal_code;
    
    /**
      * $tax_date 
      * @var string
      */
    protected $tax_date;
    
    /**
      * $channel_id 
      * @var int
      */
    protected $channel_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->supplier_id = $data["supplier_id"];
            $this->payment = $data["payment"];
            $this->reference_number = $data["reference_number"];
            $this->nominal_code = $data["nominal_code"];
            $this->tax_date = $data["tax_date"];
            $this->channel_id = $data["channel_id"];
        }
    }
    
    /**
     * Gets supplier_id
     * @return int
     */
    public function getSupplierId()
    {
        return $this->supplier_id;
    }
  
    /**
     * Sets supplier_id
     * @param int $supplier_id 
     * @return $this
     */
    public function setSupplierId($supplier_id)
    {
        
        $this->supplier_id = $supplier_id;
        return $this;
    }
    
    /**
     * Gets payment
     * @return \BrightpearlApiClient\Model\MonetaryValue
     */
    public function getPayment()
    {
        return $this->payment;
    }
  
    /**
     * Sets payment
     * @param \BrightpearlApiClient\Model\MonetaryValue $payment
     * @return $this
     */
    public function setPayment($payment)
    {
        
        $this->payment = $payment;
        return $this;
    }
    
    /**
     * Gets reference_number
     * @return string
     */
    public function getReferenceNumber()
    {
        return $this->reference_number;
    }
  
    /**
     * Sets reference_number
     * @param string $reference_number 
     * @return $this
     */
    public function setReferenceNumber($reference_number)
    {
        
        $this->reference_number = $reference_number;
        return $this;
    }
    
    /**
     * Gets nominal_code
     * @return string
     */
    public function getNominalCode()
    {
        return $this->nominal_code;
    }
  
    /**
     * Sets nominal_code
     * @param string $nominal_code 
     * @return $this
     */
    public function setNominalCode($nominal_code)
    {
        
        $this->nominal_code = $nominal_code;
        return $this;
    }
    
    /**
     * Gets tax_date
     * @return string
     */
    public function getTaxDate()
    {
        return $this->tax_date;
    }
  
    /**
     * Sets tax_date
     * @param string $tax_date 
     * @return $this
     */
    public function setTaxDate($tax_date)
    {
        
        $this->tax_date = $tax_date;
        return $this;
    }
    
    /**
     * Gets channel_id
     * @return int
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }
  
    /**
     * Sets channel_id
     * @param int $channel_id 
     * @return $this
     */
    public function setChannelId($channel_id)
    {
        
        $this->channel_id = $channel_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
