<?php
/**
 * DropShipNote
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightpearlApiClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightpearlApiClient\Model;

use \ArrayAccess;
/**
 * DropShipNote Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     BrightpearlApiClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DropShipNote implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'order_id' => 'int',
        'purchase_order_id' => 'int',
        'supplier_id' => 'int',
        'status' => '\BrightpearlApiClient\Model\DropShipNoteStatus',
        'order_rows' => 'Object', // hack here since I can't get the deserializer to deal with multiple locations per row
        'events' => '\BrightpearlApiClient\Model\Event[]',
        'shipping' => '\BrightpearlApiClient\Model\DropShipNoteShipping'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'order_id' => 'orderId',
        'purchase_order_id' => 'purchaseOrderId',
        'supplier_id' => 'supplierId',
        'status' => 'status',
        'order_rows' => 'orderRows',
        'events' => 'events',
        'shipping' => 'shipping'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'order_id' => 'setOrderId',
        'purchase_order_id' => 'setPurchaseOrderId',
        'supplier_id' => 'setSupplierId',
        'status' => 'setStatus',
        'order_rows' => 'setOrderRows',
        'events' => 'setEvents',
        'shipping' => 'setShipping'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'order_id' => 'getOrderId',
        'purchase_order_id' => 'getPurchaseOrderId',
        'supplier_id' => 'getSupplierId',
        'status' => 'getStatus',
        'order_rows' => 'getOrderRows',
        'events' => 'getEvents',
        'shipping' => 'getShipping'
    );
  
    
    /**
      * $order_id 
      * @var int
      */
    protected $order_id;
    
    /**
      * $purchase_order_id 
      * @var int
      */
    protected $purchase_order_id;
    
    /**
      * $supplier_id 
      * @var int
      */
    protected $supplier_id;
    
    /**
      * $status 
      * @var \BrightpearlApiClient\Model\DropShipNoteStatus
      */
    protected $status;
    
    /**
      * $order_rows 
      * @var \BrightpearlApiClient\Model\OrderRows
      */
    protected $order_rows;
    
    /**
      * $events 
      * @var \BrightpearlApiClient\Model\Event[]
      */
    protected $events;
    
    /**
      * $shipping 
      * @var \BrightpearlApiClient\Model\DropShipNoteShipping
      */
    protected $shipping;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->order_id = $data["order_id"];
            $this->purchase_order_id = $data["purchase_order_id"];
            $this->supplier_id = $data["supplier_id"];
            $this->status = $data["status"];
            $this->order_rows = $data["order_rows"];
            $this->events = $data["events"];
            $this->shipping = $data["shipping"];
        }
    }
    
    /**
     * Gets order_id
     * @return int
     */
    public function getOrderId()
    {
        return $this->order_id;
    }
  
    /**
     * Sets order_id
     * @param int $order_id 
     * @return $this
     */
    public function setOrderId($order_id)
    {
        
        $this->order_id = $order_id;
        return $this;
    }
    
    /**
     * Gets purchase_order_id
     * @return int
     */
    public function getPurchaseOrderId()
    {
        return $this->purchase_order_id;
    }
  
    /**
     * Sets purchase_order_id
     * @param int $purchase_order_id 
     * @return $this
     */
    public function setPurchaseOrderId($purchase_order_id)
    {
        
        $this->purchase_order_id = $purchase_order_id;
        return $this;
    }
    
    /**
     * Gets supplier_id
     * @return int
     */
    public function getSupplierId()
    {
        return $this->supplier_id;
    }
  
    /**
     * Sets supplier_id
     * @param int $supplier_id 
     * @return $this
     */
    public function setSupplierId($supplier_id)
    {
        
        $this->supplier_id = $supplier_id;
        return $this;
    }
    
    /**
     * Gets status
     * @return \BrightpearlApiClient\Model\DropShipNoteStatus
     */
    public function getStatus()
    {
        return $this->status;
    }
  
    /**
     * Sets status
     * @param \BrightpearlApiClient\Model\DropShipNoteStatus $status
     * @return $this
     */
    public function setStatus($status)
    {
        
        $this->status = $status;
        return $this;
    }
    
    /**
     * Gets order_rows
     * @return \BrightpearlApiClient\Model\OrderRows
     */
    public function getOrderRows()
    {
        return $this->order_rows;
    }
  
    /**
     * Sets order_rows
     * @param \BrightpearlApiClient\Model\OrderRows $order_rows
     * @return $this
     */
    public function setOrderRows($order_rows)
    {
        
        $this->order_rows = $order_rows;
        return $this;
    }
    
    /**
     * Gets events
     * @return \BrightpearlApiClient\Model\Event[]
     */
    public function getEvents()
    {
        return $this->events;
    }
  
    /**
     * Sets events
     * @param \BrightpearlApiClient\Model\Event[] $events
     * @return $this
     */
    public function setEvents($events)
    {
        
        $this->events = $events;
        return $this;
    }
    
    /**
     * Gets shipping
     * @return \BrightpearlApiClient\Model\DropShipNoteShipping
     */
    public function getShipping()
    {
        return $this->shipping;
    }
  
    /**
     * Sets shipping
     * @param \BrightpearlApiClient\Model\DropShipNoteShipping $shipping
     * @return $this
     */
    public function setShipping($shipping)
    {
        
        $this->shipping = $shipping;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
