<?php
/**
 * InlineResponse2008Response
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightpearlApiClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightpearlApiClient\Model;

use \ArrayAccess;
/**
 * InlineResponse2008Response Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     BrightpearlApiClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2008Response implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'resource_errors' => '\BrightpearlApiClient\Model\InlineResponse2008ResponseResourceErrors',
        'resource_statuses' => '\BrightpearlApiClient\Model\InlineResponse2008ResponseResourceStatuses'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'resource_errors' => 'resourceErrors',
        'resource_statuses' => 'resourceStatuses'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'resource_errors' => 'setResourceErrors',
        'resource_statuses' => 'setResourceStatuses'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'resource_errors' => 'getResourceErrors',
        'resource_statuses' => 'getResourceStatuses'
    );
  
    
    /**
      * $resource_errors 
      * @var \BrightpearlApiClient\Model\InlineResponse2008ResponseResourceErrors
      */
    protected $resource_errors;
    
    /**
      * $resource_statuses 
      * @var \BrightpearlApiClient\Model\InlineResponse2008ResponseResourceStatuses
      */
    protected $resource_statuses;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->resource_errors = $data["resource_errors"];
            $this->resource_statuses = $data["resource_statuses"];
        }
    }
    
    /**
     * Gets resource_errors
     * @return \BrightpearlApiClient\Model\InlineResponse2008ResponseResourceErrors
     */
    public function getResourceErrors()
    {
        return $this->resource_errors;
    }
  
    /**
     * Sets resource_errors
     * @param \BrightpearlApiClient\Model\InlineResponse2008ResponseResourceErrors $resource_errors
     * @return $this
     */
    public function setResourceErrors($resource_errors)
    {
        
        $this->resource_errors = $resource_errors;
        return $this;
    }
    
    /**
     * Gets resource_statuses
     * @return \BrightpearlApiClient\Model\InlineResponse2008ResponseResourceStatuses
     */
    public function getResourceStatuses()
    {
        return $this->resource_statuses;
    }
  
    /**
     * Sets resource_statuses
     * @param \BrightpearlApiClient\Model\InlineResponse2008ResponseResourceStatuses $resource_statuses
     * @return $this
     */
    public function setResourceStatuses($resource_statuses)
    {
        
        $this->resource_statuses = $resource_statuses;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
