<?php
/**
 * LeadSource
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightpearlApiClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightpearlApiClient\Model;

use \ArrayAccess;
/**
 * LeadSource Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     BrightpearlApiClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LeadSource implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'int',
        'owner_id' => 'int',
        'parent_id' => 'int',
        'name' => 'string',
        'is_active' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'owner_id' => 'ownerId',
        'parent_id' => 'parentId',
        'name' => 'name',
        'is_active' => 'isActive'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'owner_id' => 'setOwnerId',
        'parent_id' => 'setParentId',
        'name' => 'setName',
        'is_active' => 'setIsActive'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'owner_id' => 'getOwnerId',
        'parent_id' => 'getParentId',
        'name' => 'getName',
        'is_active' => 'getIsActive'
    );
  
    
    /**
      * $id 
      * @var int
      */
    protected $id;
    
    /**
      * $owner_id 
      * @var int
      */
    protected $owner_id;
    
    /**
      * $parent_id 
      * @var int
      */
    protected $parent_id;
    
    /**
      * $name 
      * @var string
      */
    protected $name;
    
    /**
      * $is_active 
      * @var string
      */
    protected $is_active;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->id = $data["id"];
            $this->owner_id = $data["owner_id"];
            $this->parent_id = $data["parent_id"];
            $this->name = $data["name"];
            $this->is_active = $data["is_active"];
        }
    }
    
    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param int $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets owner_id
     * @return int
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }
  
    /**
     * Sets owner_id
     * @param int $owner_id 
     * @return $this
     */
    public function setOwnerId($owner_id)
    {
        
        $this->owner_id = $owner_id;
        return $this;
    }
    
    /**
     * Gets parent_id
     * @return int
     */
    public function getParentId()
    {
        return $this->parent_id;
    }
  
    /**
     * Sets parent_id
     * @param int $parent_id 
     * @return $this
     */
    public function setParentId($parent_id)
    {
        
        $this->parent_id = $parent_id;
        return $this;
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name 
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets is_active
     * @return string
     */
    public function getIsActive()
    {
        return $this->is_active;
    }
  
    /**
     * Sets is_active
     * @param string $is_active 
     * @return $this
     */
    public function setIsActive($is_active)
    {
        
        $this->is_active = $is_active;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
