<?php
/**
 * PostGoodsInNoteGoodsMoved
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightpearlApiClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightpearlApiClient\Model;

use \ArrayAccess;
/**
 * PostGoodsInNoteGoodsMoved Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     BrightpearlApiClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostGoodsInNoteGoodsMoved implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'purchase_order_row_id' => 'int',
        'quantity' => 'int',
        'product_value' => '\BrightpearlApiClient\Model\MonetaryValue',
        'product_id' => 'int',
        'destination_location_id' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'purchase_order_row_id' => 'purchaseOrderRowId',
        'quantity' => 'quantity',
        'product_value' => 'productValue',
        'product_id' => 'productId',
        'destination_location_id' => 'destinationLocationId'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'purchase_order_row_id' => 'setPurchaseOrderRowId',
        'quantity' => 'setQuantity',
        'product_value' => 'setProductValue',
        'product_id' => 'setProductId',
        'destination_location_id' => 'setDestinationLocationId'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'purchase_order_row_id' => 'getPurchaseOrderRowId',
        'quantity' => 'getQuantity',
        'product_value' => 'getProductValue',
        'product_id' => 'getProductId',
        'destination_location_id' => 'getDestinationLocationId'
    );
  
    
    /**
      * $purchase_order_row_id 
      * @var int
      */
    protected $purchase_order_row_id;
    
    /**
      * $quantity 
      * @var int
      */
    protected $quantity;
    
    /**
      * $product_value 
      * @var \BrightpearlApiClient\Model\MonetaryValue
      */
    protected $product_value;
    
    /**
      * $product_id 
      * @var int
      */
    protected $product_id;
    
    /**
      * $destination_location_id 
      * @var int
      */
    protected $destination_location_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->purchase_order_row_id = $data["purchase_order_row_id"];
            $this->quantity = $data["quantity"];
            $this->product_value = $data["product_value"];
            $this->product_id = $data["product_id"];
            $this->destination_location_id = $data["destination_location_id"];
        }
    }
    
    /**
     * Gets purchase_order_row_id
     * @return int
     */
    public function getPurchaseOrderRowId()
    {
        return $this->purchase_order_row_id;
    }
  
    /**
     * Sets purchase_order_row_id
     * @param int $purchase_order_row_id 
     * @return $this
     */
    public function setPurchaseOrderRowId($purchase_order_row_id)
    {
        
        $this->purchase_order_row_id = $purchase_order_row_id;
        return $this;
    }
    
    /**
     * Gets quantity
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }
  
    /**
     * Sets quantity
     * @param int $quantity 
     * @return $this
     */
    public function setQuantity($quantity)
    {
        
        $this->quantity = $quantity;
        return $this;
    }
    
    /**
     * Gets product_value
     * @return \BrightpearlApiClient\Model\MonetaryValue
     */
    public function getProductValue()
    {
        return $this->product_value;
    }
  
    /**
     * Sets product_value
     * @param \BrightpearlApiClient\Model\MonetaryValue $product_value
     * @return $this
     */
    public function setProductValue($product_value)
    {
        
        $this->product_value = $product_value;
        return $this;
    }
    
    /**
     * Gets product_id
     * @return int
     */
    public function getProductId()
    {
        return $this->product_id;
    }
  
    /**
     * Sets product_id
     * @param int $product_id 
     * @return $this
     */
    public function setProductId($product_id)
    {
        
        $this->product_id = $product_id;
        return $this;
    }
    
    /**
     * Gets destination_location_id
     * @return int
     */
    public function getDestinationLocationId()
    {
        return $this->destination_location_id;
    }
  
    /**
     * Sets destination_location_id
     * @param int $destination_location_id 
     * @return $this
     */
    public function setDestinationLocationId($destination_location_id)
    {
        
        $this->destination_location_id = $destination_location_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
