<?php
/**
 * SearchResponseResponseMetaData
 *
 * PHP version 5
 *
 * @category Class
 * @package  BrightpearlApiClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BrightpearlApiClient\Model;

use \ArrayAccess;
/**
 * SearchResponseResponseMetaData Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     BrightpearlApiClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchResponseResponseMetaData implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'results_returned' => 'int',
        'last_result' => 'int',
        'columns' => '\BrightpearlApiClient\Model\SearchColumn[]',
        'sorting' => '\BrightpearlApiClient\Model\SearchResponseResponseMetaDataSorting[]',
        'first_result' => 'int',
        'results_available' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'results_returned' => 'resultsReturned',
        'last_result' => 'lastResult',
        'columns' => 'columns',
        'sorting' => 'sorting',
        'first_result' => 'firstResult',
        'results_available' => 'resultsAvailable'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'results_returned' => 'setResultsReturned',
        'last_result' => 'setLastResult',
        'columns' => 'setColumns',
        'sorting' => 'setSorting',
        'first_result' => 'setFirstResult',
        'results_available' => 'setResultsAvailable'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'results_returned' => 'getResultsReturned',
        'last_result' => 'getLastResult',
        'columns' => 'getColumns',
        'sorting' => 'getSorting',
        'first_result' => 'getFirstResult',
        'results_available' => 'getResultsAvailable'
    );
  
    
    /**
      * $results_returned 
      * @var int
      */
    protected $results_returned;
    
    /**
      * $last_result 
      * @var int
      */
    protected $last_result;
    
    /**
      * $columns 
      * @var \BrightpearlApiClient\Model\SearchColumn[]
      */
    protected $columns;
    
    /**
      * $sorting 
      * @var \BrightpearlApiClient\Model\SearchResponseResponseMetaDataSorting[]
      */
    protected $sorting;
    
    /**
      * $first_result 
      * @var int
      */
    protected $first_result;
    
    /**
      * $results_available 
      * @var int
      */
    protected $results_available;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->results_returned = $data["results_returned"];
            $this->last_result = $data["last_result"];
            $this->columns = $data["columns"];
            $this->sorting = $data["sorting"];
            $this->first_result = $data["first_result"];
            $this->results_available = $data["results_available"];
        }
    }
    
    /**
     * Gets results_returned
     * @return int
     */
    public function getResultsReturned()
    {
        return $this->results_returned;
    }
  
    /**
     * Sets results_returned
     * @param int $results_returned 
     * @return $this
     */
    public function setResultsReturned($results_returned)
    {
        
        $this->results_returned = $results_returned;
        return $this;
    }
    
    /**
     * Gets last_result
     * @return int
     */
    public function getLastResult()
    {
        return $this->last_result;
    }
  
    /**
     * Sets last_result
     * @param int $last_result 
     * @return $this
     */
    public function setLastResult($last_result)
    {
        
        $this->last_result = $last_result;
        return $this;
    }
    
    /**
     * Gets columns
     * @return \BrightpearlApiClient\Model\SearchColumn[]
     */
    public function getColumns()
    {
        return $this->columns;
    }
  
    /**
     * Sets columns
     * @param \BrightpearlApiClient\Model\SearchColumn[] $columns
     * @return $this
     */
    public function setColumns($columns)
    {
        
        $this->columns = $columns;
        return $this;
    }
    
    /**
     * Gets sorting
     * @return \BrightpearlApiClient\Model\SearchResponseResponseMetaDataSorting[]
     */
    public function getSorting()
    {
        return $this->sorting;
    }
  
    /**
     * Sets sorting
     * @param \BrightpearlApiClient\Model\SearchResponseResponseMetaDataSorting[] $sorting
     * @return $this
     */
    public function setSorting($sorting)
    {
        
        $this->sorting = $sorting;
        return $this;
    }
    
    /**
     * Gets first_result
     * @return int
     */
    public function getFirstResult()
    {
        return $this->first_result;
    }
  
    /**
     * Sets first_result
     * @param int $first_result 
     * @return $this
     */
    public function setFirstResult($first_result)
    {
        
        $this->first_result = $first_result;
        return $this;
    }
    
    /**
     * Gets results_available
     * @return int
     */
    public function getResultsAvailable()
    {
        return $this->results_available;
    }
  
    /**
     * Sets results_available
     * @param int $results_available 
     * @return $this
     */
    public function setResultsAvailable($results_available)
    {
        
        $this->results_available = $results_available;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\BrightpearlApiClient\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
