<?php

namespace Annex\TenantBundle\Repository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function getSettingsKeys()
    {
        $validKeys = array(
            'org_timezone',
            'org_name',
            'org_country',
            'org_email',
            'org_cellphone',
            'zd_domain',
            'zd_user_email',
            'zd_api_token',
        );

        return $validKeys;
    }

    /**
     * @return array
     */
    public function getAllSettings()
    {
        $settingsArray = array();

        // initialise the settings array in case the DB has no values
        $keys = $this->getSettingsKeys();
        foreach ($keys AS $key) {
            $settingsArray[$key] = '';
        }

        $settings = $this->findAll();
        foreach ($settings AS $setting) {
            /** @var $setting \Annex\TenantBundle\Entity\Setting */
            $setupKey   = $setting->getSetupKey();
            $setupValue = $setting->getSetupValue();
            $settingsArray[$setupKey] = $setupValue;
        }

        return $settingsArray;
    }

    /**
     * @param $key
     * @return bool
     */
    public function isValidSettingsKey($key)
    {
        $validKeys = $this->getSettingsKeys();

        if (in_array($key, $validKeys)) {
            return true;
        }

        return false;
    }

}
